shell:
  program: /opt/homebrew/bin/fish

window:
  dynamic_padding: false
  startup_mode: Maximized
  decorations: buttonless
  option_as_alt: Both

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: "0x282828"
    # soft contrast: background = '0x32302f'
    foreground: "0xebdbb2"

  # Normal colors
  normal:
    black: "0x282828"
    red: "0xcc241d"
    green: "0x98971a"
    yellow: "0xd79921"
    blue: "0x458588"
    magenta: "0xb16286"
    cyan: "0x689d6a"
    white: "0xa89984"

  # Bright colors
  bright:
    black: "0x928374"
    red: "0xfb4934"
    green: "0xb8bb26"
    yellow: "0xfabd2f"
    blue: "0x83a598"
    magenta: "0xd3869b"
    cyan: "0x8ec07c"
    white: "0xebdbb2"

font:
  size: 15
  normal:
    family: MesloLGS Nerd Font Mono
    style: Regular
  bold:
    family: MesloLGS Nerd Font Mono
    style: Bold
  italic:
    family: MesloLGS Nerd Font Mono
    style: Italic
  bold_italic:
    family: MesloLGS Nerd Font Mono
    style: Bold Italic

key_bindings:
  # cmd + , to open config file in nvim
  - key: Comma
    mods: Command
    command:
      program: "/Applications/Alacritty.app/Contents/MacOS/alacritty"
      args: ["-e", "fish", "--login", "-i", "-c", "nvim ~/.alacritty.yml"]
  # make sure ctrl + space works in vim
  - { key: Space, mods: Control, chars: "\x00" }
  # workaround for https://github.com/alacritty/alacritty/issues/1606
  # - { key: Back, action: ReceiveChar }

env:
  LC_ALL: zh_CN.UTF-8
  TERM: xterm-256color

input:
  alt_send_esc: true
