return {
    -- {
    --     "zbirenbaum/copilot.lua",
    --     cmd = "Copilot",
    --     event = "InsertEnter",
    --     config = function()
    --         require("copilot").setup({
    --             suggestion = {
    --                 enabled = true,
    --                 auto_trigger = false,
    --                 debounce = 75,
    --                 keymap = {
    --                     accept = "¬",
    --                     accept_word = false,
    --                     accept_line = false,
    --                     next = "‘",
    --                     prev = "“",
    --                     dismiss = "<C-]>",
    --                 },
    --             },
    --         })
    --     end,
    -- },
    -- {
    --     "zbirenbaum/copilot-cmp",
    --     dependencies = { "zbirenbaum/copilot.lua" },
    --     config = function()
    --         require("copilot_cmp").setup()
    --     end
    -- },
}
